version: "3.7"

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:5.7
    container_name: mercado-pago-mysql
    volumes:
      - "mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mercado_pago
      - MYSQL_USER=user
      - MYSQL_PASSWORD=qwer1234

  app:
    image: ambientum/php:7.3-nginx
    container_name: mercado-pago-app
    volumes:
      - ".:/var/www/app"
    ports:
      - "80:8080"
